"""empty message

Revision ID: ebbc0add8c4f
Revises: cec20af2bd0a
Create Date: 2019-11-21 00:03:10.253238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebbc0add8c4f'
down_revision = 'cec20af2bd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'short_id',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    op.create_unique_constraint(None, 'roles', ['short_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'short_id',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###
